//  MOCK DATABASE
import type { Listing, AdminAction } from "./types";

//admin users
export const adminUsers = [
  {
    id: "1",
    name: "Admin User",
    email: "admin@yopmail.com",
    role: "admin",
    password: "$2a$12$u7ysxsJEcoG8VjtrVlMhBuEKo6QvUcpLDTh5RAnJpnTCAvQ0qd7..", //Admin@123
  },
  {
    id: "2",
    name: "Sandeep Yadav",
    email: "sandeep@gmail.com",
    role: "admin",
    password: "$2a$12$r2VBbuTgRQij1apBK645d.w2sey0AKBDOgL5GO/HYygSz4r97faKm", //sandeep@786
  },
];

// car rentals list
export const listings: Listing[] = [
  {
    id: 1,
    userId: 1,
    userName: "Tammy Frazier",
    userEmail: "rebecca77@gmail.com",
    make: "Chevrolet",
    model: "Tahoe",
    year: 2020,
    pricePerDay: 49.32,
    location: "Port Alejandromouth, IL",
    description: "Project reflect spring its again.",
    features: [
      "Heated Seats",
      "AC",
      "Apple CarPlay",
      "Leather Seats",
      "Cruise Control",
    ],
    status: "rejected",
    reviewedBy: "Jerry Hill",
    reviewedAt: "2025-04-23T20:39:52",
    createdAt: "2025-03-20T14:13:59",
    updatedAt: "2025-03-20T14:13:59",
  },
  {
    id: 2,
    userId: 2,
    userName: "Douglas Bailey",
    userEmail: "xpeterson@simpson.com",
    make: "Tesla",
    model: "Model X",
    year: 2023,
    pricePerDay: 90.56,
    location: "East Debra, ID",
    description: "Tax quality standard mother quality.",
    features: [
      "Cruise Control",
      "GPS",
      "Sunroof",
      "All-Wheel Drive",
      "Android Auto",
    ],
    status: "approved",
    reviewedBy: "Daniel Clay",
    reviewedAt: "2025-03-19T12:59:45",
    createdAt: "2025-07-04T19:23:07",
    updatedAt: "2025-07-04T19:23:07",
  },
  {
    id: 3,
    userId: 3,
    userName: "Mr. Johnny Nunez",
    userEmail: "rwoods@yahoo.com",
    make: "Kia",
    model: "Sorento",
    year: 2016,
    pricePerDay: 81.03,
    location: "Branchborough, MD",
    description: "Rise near mention there back officer.",
    features: ["GPS", "AC", "Sunroof", "Backup Camera"],
    status: "approved",
    reviewedBy: "Shawn Morales",
    reviewedAt: "2025-06-24T20:46:46",
    createdAt: "2025-06-16T20:13:51",
    updatedAt: "2025-06-16T20:13:51",
  },
  {
    id: 4,
    userId: 4,
    userName: "Richard Flynn",
    userEmail: "nrose@gmail.com",
    make: "Honda",
    model: "Accord",
    year: 2022,
    pricePerDay: 103.47,
    location: "Wrighttown, AL",
    description: "Wonder two edge represent grow simply.",
    features: [
      "All-Wheel Drive",
      "Backup Camera",
      "AC",
      "Heated Seats",
      "Leather Seats",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-10-22T15:27:42",
    updatedAt: "2024-10-22T15:27:42",
  },
  {
    id: 5,
    userId: 5,
    userName: "Albert Williams",
    userEmail: "nathanalexander@yahoo.com",
    make: "Toyota",
    model: "Corolla",
    year: 2022,
    pricePerDay: 104.9,
    location: "South Anthony, TX",
    description: "Appear accept quality.",
    features: [
      "Leather Seats",
      "GPS",
      "All-Wheel Drive",
      "Sunroof",
      "Apple CarPlay",
    ],
    status: "approved",
    reviewedBy: "Connie Campbell",
    reviewedAt: "2025-05-18T15:58:27",
    createdAt: "2024-09-22T04:19:20",
    updatedAt: "2024-09-22T04:19:20",
  },
  {
    id: 6,
    userId: 6,
    userName: "Douglas Olson",
    userEmail: "jeffrey57@hotmail.com",
    make: "Honda",
    model: "Accord",
    year: 2020,
    pricePerDay: 50.3,
    location: "Tylerview, AL",
    description: "Debate though single collection focus near cold.",
    features: ["Apple CarPlay", "AC", "Bluetooth"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-09-27T19:09:53",
    updatedAt: "2024-09-27T19:09:53",
  },
  {
    id: 7,
    userId: 7,
    userName: "Alyssa Spears",
    userEmail: "christine17@jordan.com",
    make: "Honda",
    model: "Accord",
    year: 2017,
    pricePerDay: 49.63,
    location: "South Michael, AK",
    description: "Meet knowledge ask form.",
    features: ["Android Auto", "Heated Seats", "Sunroof"],
    status: "rejected",
    reviewedBy: "Patrick Thomas",
    reviewedAt: "2025-01-31T14:48:16",
    createdAt: "2024-09-22T15:21:00",
    updatedAt: "2024-09-22T15:21:00",
  },
  {
    id: 8,
    userId: 8,
    userName: "Christine Jones",
    userEmail: "duncanmarissa@herrera-adams.biz",
    make: "Kia",
    model: "Sorento",
    year: 2021,
    pricePerDay: 52.83,
    location: "Port Kellyfurt, OH",
    description: "Social six common bit tough after.",
    features: ["Android Auto", "Bluetooth", "Sunroof", "Backup Camera"],
    status: "rejected",
    reviewedBy: "Dennis Palmer",
    reviewedAt: "2025-06-06T13:11:28",
    createdAt: "2025-06-28T23:35:09",
    updatedAt: "2025-06-28T23:35:09",
  },
  {
    id: 9,
    userId: 9,
    userName: "Timothy Wood",
    userEmail: "sarahrojas@yahoo.com",
    make: "Audi",
    model: "Q7",
    year: 2015,
    pricePerDay: 84.84,
    location: "Jasonmouth, OR",
    description: "Experience score say color direction include.",
    features: [
      "AC",
      "Cruise Control",
      "Android Auto",
      "All-Wheel Drive",
      "Bluetooth",
      "Apple CarPlay",
    ],
    status: "approved",
    reviewedBy: "Isaac Pena",
    reviewedAt: "2025-04-30T04:09:18",
    createdAt: "2025-05-10T22:06:58",
    updatedAt: "2025-05-10T22:06:58",
  },
  {
    id: 10,
    userId: 10,
    userName: "David Harmon",
    userEmail: "yrichardson@yahoo.com",
    make: "Hyundai",
    model: "Tucson",
    year: 2018,
    pricePerDay: 43.06,
    location: "Lake Kevin, PA",
    description: "Wrong paper morning several operation line speak.",
    features: ["Backup Camera", "Bluetooth", "Apple CarPlay", "Leather Seats"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-12-21T20:13:06",
    updatedAt: "2024-12-21T20:13:06",
  },
  {
    id: 11,
    userId: 11,
    userName: "Tom Berry MD",
    userEmail: "rwhite@hotmail.com",
    make: "Honda",
    model: "CR-V",
    year: 2015,
    pricePerDay: 65.09,
    location: "Davidstad, ME",
    description: "Short computer behavior near maintain it billion.",
    features: [
      "Apple CarPlay",
      "Cruise Control",
      "Sunroof",
      "AC",
      "Heated Seats",
      "GPS",
    ],
    status: "rejected",
    reviewedBy: "Jamie Hutchinson",
    reviewedAt: "2025-07-08T18:24:43",
    createdAt: "2024-11-02T08:32:21",
    updatedAt: "2024-11-02T08:32:21",
  },
  {
    id: 12,
    userId: 12,
    userName: "Vanessa Cohen",
    userEmail: "zstephens@hotmail.com",
    make: "Tesla",
    model: "Model X",
    year: 2016,
    pricePerDay: 97.28,
    location: "Calvinside, IA",
    description: "Argue discussion color be.",
    features: [
      "All-Wheel Drive",
      "Heated Seats",
      "Backup Camera",
      "Sunroof",
      "Bluetooth",
    ],
    status: "rejected",
    reviewedBy: "Sandra Hunt",
    reviewedAt: "2025-02-14T23:38:56",
    createdAt: "2025-05-18T12:54:35",
    updatedAt: "2025-05-18T12:54:35",
  },
  {
    id: 13,
    userId: 13,
    userName: "George Dunn",
    userEmail: "christinabrown@gmail.com",
    make: "BMW",
    model: "X5",
    year: 2023,
    pricePerDay: 113.94,
    location: "Dianestad, OR",
    description: "Interest suddenly game national let.",
    features: ["Sunroof", "Heated Seats", "Leather Seats"],
    status: "rejected",
    reviewedBy: "Daniel Thompson",
    reviewedAt: "2025-01-04T06:55:48",
    createdAt: "2025-05-25T11:55:25",
    updatedAt: "2025-05-25T11:55:25",
  },
  {
    id: 14,
    userId: 14,
    userName: "Jody Thomas",
    userEmail: "david24@carrillo.com",
    make: "Ford",
    model: "Explorer",
    year: 2020,
    pricePerDay: 87.31,
    location: "North Joseshire, NJ",
    description: "Should ask major him little Mr while.",
    features: ["Backup Camera", "Sunroof", "Leather Seats"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-05-06T01:06:04",
    updatedAt: "2025-05-06T01:06:04",
  },
  {
    id: 15,
    userId: 15,
    userName: "Ashley Young",
    userEmail: "hicksdenise@gmail.com",
    make: "Tesla",
    model: "Model 3",
    year: 2024,
    pricePerDay: 107.99,
    location: "Hillton, SC",
    description: "Old baby life major treatment listen capital sport.",
    features: ["Apple CarPlay", "AC", "Sunroof"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-05-07T15:58:18",
    updatedAt: "2025-05-07T15:58:18",
  },
  {
    id: 16,
    userId: 16,
    userName: "Diana Golden",
    userEmail: "ksantiago@gmail.com",
    make: "BMW",
    model: "X3",
    year: 2016,
    pricePerDay: 99.4,
    location: "Martinville, VT",
    description: "Back work support take.",
    features: ["Apple CarPlay", "Leather Seats", "Android Auto"],
    status: "approved",
    reviewedBy: "Holly Sullivan",
    reviewedAt: "2025-04-29T17:44:24",
    createdAt: "2025-05-07T15:52:07",
    updatedAt: "2025-05-07T15:52:07",
  },
  {
    id: 17,
    userId: 17,
    userName: "Isaiah Young",
    userEmail: "rfreeman@smith-hines.com",
    make: "Audi",
    model: "Q5",
    year: 2020,
    pricePerDay: 58.47,
    location: "East Haleyside, OR",
    description: "Man collection as so.",
    features: ["Cruise Control", "AC", "Bluetooth"],
    status: "approved",
    reviewedBy: "Julia Moore",
    reviewedAt: "2025-04-23T00:09:19",
    createdAt: "2025-02-22T11:45:51",
    updatedAt: "2025-02-22T11:45:51",
  },
  {
    id: 18,
    userId: 18,
    userName: "Jordan Tucker",
    userEmail: "eholland@yahoo.com",
    make: "Hyundai",
    model: "Tucson",
    year: 2015,
    pricePerDay: 49.67,
    location: "Sharonborough, MN",
    description: "Year wall whole entire leave human.",
    features: ["Cruise Control", "All-Wheel Drive", "Android Auto"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-07-13T06:08:35",
    updatedAt: "2024-07-13T06:08:35",
  },
  {
    id: 19,
    userId: 19,
    userName: "Jessica Hughes",
    userEmail: "shellysanchez@marshall-lane.com",
    make: "Hyundai",
    model: "Tucson",
    year: 2017,
    pricePerDay: 99.02,
    location: "Charlesshire, SC",
    description: "Article suggest image network main perhaps.",
    features: [
      "Bluetooth",
      "Sunroof",
      "Backup Camera",
      "Leather Seats",
      "Cruise Control",
      "AC",
    ],
    status: "rejected",
    reviewedBy: "Dennis Henderson",
    reviewedAt: "2025-02-10T06:45:18",
    createdAt: "2024-08-08T14:04:39",
    updatedAt: "2024-08-08T14:04:39",
  },
  {
    id: 20,
    userId: 20,
    userName: "Russell Rosales",
    userEmail: "smithgabriel@gmail.com",
    make: "Hyundai",
    model: "Elantra",
    year: 2017,
    pricePerDay: 34.14,
    location: "Lake Amy, MS",
    description: "East rule raise military over international decision foot.",
    features: [
      "All-Wheel Drive",
      "Apple CarPlay",
      "AC",
      "Sunroof",
      "Cruise Control",
    ],
    status: "approved",
    reviewedBy: "Michael Thompson",
    reviewedAt: "2025-04-20T20:40:23",
    createdAt: "2025-04-06T07:56:54",
    updatedAt: "2025-04-06T07:56:54",
  },
  {
    id: 21,
    userId: 21,
    userName: "Michael Smith",
    userEmail: "rogerscharles@yahoo.com",
    make: "Hyundai",
    model: "Elantra",
    year: 2020,
    pricePerDay: 115.01,
    location: "Rosestad, RI",
    description: "Plan can really off help sometimes.",
    features: ["Backup Camera", "Sunroof", "GPS", "AC"],
    status: "rejected",
    reviewedBy: "Kathleen Montoya",
    reviewedAt: "2025-05-30T19:57:35",
    createdAt: "2024-11-26T14:23:42",
    updatedAt: "2024-11-26T14:23:42",
  },
  {
    id: 22,
    userId: 22,
    userName: "Judy Martinez",
    userEmail: "angelica85@johnson.com",
    make: "BMW",
    model: "3 Series",
    year: 2021,
    pricePerDay: 72.45,
    location: "Figueroashire, TN",
    description: "Current reduce raise study choose loss.",
    features: ["Android Auto", "Cruise Control", "Sunroof"],
    status: "approved",
    reviewedBy: "Jennifer Vasquez",
    reviewedAt: "2025-06-26T22:06:45",
    createdAt: "2025-05-26T14:49:33",
    updatedAt: "2025-05-26T14:49:33",
  },
  {
    id: 23,
    userId: 23,
    userName: "Christopher Miles",
    userEmail: "sschmidt@wilson.com",
    make: "Chevrolet",
    model: "Equinox",
    year: 2020,
    pricePerDay: 43.46,
    location: "Lake David, FL",
    description: "Large teacher chair.",
    features: ["GPS", "All-Wheel Drive", "Heated Seats"],
    status: "approved",
    reviewedBy: "Tracey Smith",
    reviewedAt: "2025-06-10T21:46:13",
    createdAt: "2025-06-08T16:06:52",
    updatedAt: "2025-06-08T16:06:52",
  },
  {
    id: 24,
    userId: 24,
    userName: "Ronald Hansen",
    userEmail: "brookskimberly@jenkins.com",
    make: "Honda",
    model: "CR-V",
    year: 2015,
    pricePerDay: 41.29,
    location: "North Grace, PA",
    description: "Push medical significant national.",
    features: [
      "Sunroof",
      "GPS",
      "Cruise Control",
      "All-Wheel Drive",
      "Backup Camera",
      "Android Auto",
    ],
    status: "approved",
    reviewedBy: "Margaret Thompson",
    reviewedAt: "2025-03-11T20:09:25",
    createdAt: "2024-11-14T09:33:06",
    updatedAt: "2024-11-14T09:33:06",
  },
  {
    id: 25,
    userId: 25,
    userName: "Benjamin Andersen",
    userEmail: "lindsay44@allison-jackson.com",
    make: "Hyundai",
    model: "Santa Fe",
    year: 2018,
    pricePerDay: 111.18,
    location: "New Tylertown, MN",
    description: "Production little after information when.",
    features: [
      "Android Auto",
      "Heated Seats",
      "Apple CarPlay",
      "AC",
      "Sunroof",
      "Bluetooth",
    ],
    status: "rejected",
    reviewedBy: "Suzanne Lee",
    reviewedAt: "2025-03-07T11:36:20",
    createdAt: "2024-11-29T07:05:59",
    updatedAt: "2024-11-29T07:05:59",
  },
  {
    id: 26,
    userId: 26,
    userName: "Tina Willis",
    userEmail: "thomaselizabeth@underwood-lane.org",
    make: "Kia",
    model: "Sorento",
    year: 2023,
    pricePerDay: 106.64,
    location: "Fowlermouth, DC",
    description: "Represent difficult parent item.",
    features: [
      "GPS",
      "Cruise Control",
      "Backup Camera",
      "All-Wheel Drive",
      "Leather Seats",
      "Heated Seats",
    ],
    status: "rejected",
    reviewedBy: "Doris Hawkins",
    reviewedAt: "2025-03-31T13:03:37",
    createdAt: "2025-05-19T09:00:39",
    updatedAt: "2025-05-19T09:00:39",
  },
  {
    id: 27,
    userId: 27,
    userName: "Victoria Carr",
    userEmail: "wwilliams@gmail.com",
    make: "Toyota",
    model: "Corolla",
    year: 2015,
    pricePerDay: 57.93,
    location: "South Courtney, NH",
    description: "Line read deep product.",
    features: [
      "Backup Camera",
      "AC",
      "Apple CarPlay",
      "Sunroof",
      "GPS",
      "All-Wheel Drive",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-02-18T15:44:06",
    updatedAt: "2025-02-18T15:44:06",
  },
  {
    id: 28,
    userId: 28,
    userName: "Thomas Norton",
    userEmail: "joshua01@barnett-gross.com",
    make: "Kia",
    model: "Sportage",
    year: 2020,
    pricePerDay: 82.64,
    location: "Popemouth, SC",
    description: "Finally argue look.",
    features: ["GPS", "Sunroof", "AC", "Leather Seats", "Cruise Control"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-09-17T12:27:57",
    updatedAt: "2024-09-17T12:27:57",
  },
  {
    id: 29,
    userId: 29,
    userName: "Phillip Jimenez",
    userEmail: "hrobinson@mendoza-austin.com",
    make: "BMW",
    model: "3 Series",
    year: 2018,
    pricePerDay: 107.78,
    location: "Kellerland, HI",
    description: "Real government improve hour.",
    features: ["Sunroof", "Bluetooth", "Leather Seats"],
    status: "approved",
    reviewedBy: "Jasmine Lane",
    reviewedAt: "2025-06-08T10:14:39",
    createdAt: "2025-04-24T08:45:08",
    updatedAt: "2025-04-24T08:45:08",
  },
  {
    id: 30,
    userId: 30,
    userName: "Jerry Franklin",
    userEmail: "jimenezgabriel@howard.info",
    make: "Tesla",
    model: "Model 3",
    year: 2016,
    pricePerDay: 107.19,
    location: "Gambletown, OH",
    description: "Different cut edge out fine common.",
    features: ["Heated Seats", "Android Auto", "Bluetooth"],
    status: "rejected",
    reviewedBy: "Linda Friedman",
    reviewedAt: "2025-05-01T00:05:01",
    createdAt: "2024-11-25T02:38:46",
    updatedAt: "2024-11-25T02:38:46",
  },
  {
    id: 31,
    userId: 31,
    userName: "Harry Owens",
    userEmail: "xolsen@yahoo.com",
    make: "Tesla",
    model: "Model 3",
    year: 2020,
    pricePerDay: 54.72,
    location: "Bakerhaven, CT",
    description: "Note study care Congress beautiful.",
    features: [
      "Leather Seats",
      "Heated Seats",
      "Cruise Control",
      "Backup Camera",
      "Sunroof",
    ],
    status: "rejected",
    reviewedBy: "Nathaniel Flores",
    reviewedAt: "2025-07-02T11:39:38",
    createdAt: "2025-05-26T03:03:19",
    updatedAt: "2025-05-26T03:03:19",
  },
  {
    id: 32,
    userId: 32,
    userName: "Mark Bautista",
    userEmail: "austinabigail@hotmail.com",
    make: "Kia",
    model: "Soul",
    year: 2020,
    pricePerDay: 35.54,
    location: "North Robertfurt, TX",
    description: "Wind to include have interesting notice.",
    features: [
      "AC",
      "All-Wheel Drive",
      "Android Auto",
      "Leather Seats",
      "Apple CarPlay",
      "GPS",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-01-19T13:42:11",
    updatedAt: "2025-01-19T13:42:11",
  },
  {
    id: 33,
    userId: 33,
    userName: "Alexis Franklin",
    userEmail: "amysharp@gmail.com",
    make: "Tesla",
    model: "Model 3",
    year: 2021,
    pricePerDay: 36.68,
    location: "Lake Kimberlychester, WV",
    description: "Century relationship skill many example ahead tell past.",
    features: [
      "GPS",
      "All-Wheel Drive",
      "Cruise Control",
      "Heated Seats",
      "Apple CarPlay",
    ],
    status: "approved",
    reviewedBy: "James Lee",
    reviewedAt: "2025-04-16T11:50:54",
    createdAt: "2025-03-31T16:55:49",
    updatedAt: "2025-03-31T16:55:49",
  },
  {
    id: 34,
    userId: 34,
    userName: "Alexander Ortega",
    userEmail: "jared43@yahoo.com",
    make: "Kia",
    model: "Sportage",
    year: 2024,
    pricePerDay: 107.52,
    location: "Mistyborough, UT",
    description: "Some often what.",
    features: [
      "Backup Camera",
      "Heated Seats",
      "Apple CarPlay",
      "Leather Seats",
      "All-Wheel Drive",
    ],
    status: "rejected",
    reviewedBy: "Wendy Rivera",
    reviewedAt: "2025-03-16T02:11:36",
    createdAt: "2024-10-22T04:48:52",
    updatedAt: "2024-10-22T04:48:52",
  },
  {
    id: 35,
    userId: 35,
    userName: "Jennifer Lowe",
    userEmail: "frank17@hotmail.com",
    make: "Nissan",
    model: "Altima",
    year: 2023,
    pricePerDay: 68.09,
    location: "Rhodesburgh, NM",
    description: "Society song want police water.",
    features: [
      "AC",
      "Leather Seats",
      "Cruise Control",
      "All-Wheel Drive",
      "Sunroof",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-07-07T17:22:42",
    updatedAt: "2025-07-07T17:22:42",
  },
  {
    id: 36,
    userId: 36,
    userName: "Wendy Stone",
    userEmail: "gary35@hotmail.com",
    make: "Ford",
    model: "Explorer",
    year: 2022,
    pricePerDay: 86.93,
    location: "Andrewbury, WA",
    description: "Owner ability old individual body.",
    features: [
      "All-Wheel Drive",
      "Heated Seats",
      "Sunroof",
      "Leather Seats",
      "Cruise Control",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-11-09T21:15:51",
    updatedAt: "2024-11-09T21:15:51",
  },
  {
    id: 37,
    userId: 37,
    userName: "Heather Yang",
    userEmail: "fyoung@hotmail.com",
    make: "Toyota",
    model: "Corolla",
    year: 2016,
    pricePerDay: 41.63,
    location: "North Carmenmouth, AL",
    description: "Song rise offer air green.",
    features: [
      "All-Wheel Drive",
      "Leather Seats",
      "Heated Seats",
      "Cruise Control",
      "GPS",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-03-29T18:26:51",
    updatedAt: "2025-03-29T18:26:51",
  },
  {
    id: 38,
    userId: 38,
    userName: "Alicia Wood",
    userEmail: "hboone@lee.com",
    make: "Toyota",
    model: "RAV4",
    year: 2022,
    pricePerDay: 108.32,
    location: "West Robert, OK",
    description: "Type mother she choose century.",
    features: [
      "Backup Camera",
      "Leather Seats",
      "All-Wheel Drive",
      "Cruise Control",
      "Sunroof",
      "GPS",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-02-24T14:18:37",
    updatedAt: "2025-02-24T14:18:37",
  },
  {
    id: 39,
    userId: 39,
    userName: "Ricky Burns",
    userEmail: "hudsonwilliam@bennett.com",
    make: "Audi",
    model: "Q7",
    year: 2020,
    pricePerDay: 35.65,
    location: "Leetown, NJ",
    description: "Officer age issue anyone arm least garden number.",
    features: ["Backup Camera", "Apple CarPlay", "Bluetooth"],
    status: "rejected",
    reviewedBy: "Lauren Miranda",
    reviewedAt: "2025-05-21T17:03:01",
    createdAt: "2024-10-01T16:45:41",
    updatedAt: "2024-10-01T16:45:41",
  },
  {
    id: 40,
    userId: 40,
    userName: "Phillip Taylor",
    userEmail: "thomascarpenter@henry.com",
    make: "Toyota",
    model: "Corolla",
    year: 2015,
    pricePerDay: 41.97,
    location: "New Denisefurt, IL",
    description: "Between million west so.",
    features: [
      "AC",
      "All-Wheel Drive",
      "Heated Seats",
      "Apple CarPlay",
      "Bluetooth",
      "Cruise Control",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-08-10T12:26:05",
    updatedAt: "2024-08-10T12:26:05",
  },
  {
    id: 41,
    userId: 41,
    userName: "Marcus Gray",
    userEmail: "moorebrian@yahoo.com",
    make: "Toyota",
    model: "Corolla",
    year: 2022,
    pricePerDay: 81.48,
    location: "Donaldchester, MA",
    description: "Mind although world true inside apply.",
    features: ["Cruise Control", "Heated Seats", "Android Auto"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-07-21T06:18:56",
    updatedAt: "2024-07-21T06:18:56",
  },
  {
    id: 42,
    userId: 42,
    userName: "Johnny Wilson",
    userEmail: "bmcclure@sharp.net",
    make: "Chevrolet",
    model: "Malibu",
    year: 2020,
    pricePerDay: 75.3,
    location: "New Sarah, GA",
    description: "Local market professor record issue people.",
    features: [
      "Heated Seats",
      "Apple CarPlay",
      "Backup Camera",
      "GPS",
      "Android Auto",
    ],
    status: "rejected",
    reviewedBy: "Randy Hudson Jr.",
    reviewedAt: "2025-05-24T09:18:18",
    createdAt: "2024-08-31T05:46:38",
    updatedAt: "2024-08-31T05:46:38",
  },
  {
    id: 43,
    userId: 43,
    userName: "Michelle Sullivan",
    userEmail: "mendezjason@hotmail.com",
    make: "Nissan",
    model: "Rogue",
    year: 2021,
    pricePerDay: 38.88,
    location: "Castroside, WY",
    description:
      "Policy agreement stop responsibility series modern rise course.",
    features: ["Backup Camera", "Apple CarPlay", "GPS"],
    status: "approved",
    reviewedBy: "Katelyn Nicholson",
    reviewedAt: "2025-05-23T19:48:40",
    createdAt: "2024-07-22T18:38:01",
    updatedAt: "2024-07-22T18:38:01",
  },
  {
    id: 44,
    userId: 44,
    userName: "Jessica Mendez",
    userEmail: "bshaffer@carr.info",
    make: "Hyundai",
    model: "Elantra",
    year: 2018,
    pricePerDay: 62.4,
    location: "South Kevin, NV",
    description: "Return against newspaper much benefit health.",
    features: ["Cruise Control", "Backup Camera", "Bluetooth", "Android Auto"],
    status: "approved",
    reviewedBy: "Mrs. Elizabeth Porter",
    reviewedAt: "2025-02-01T22:18:12",
    createdAt: "2025-04-15T09:34:44",
    updatedAt: "2025-04-15T09:34:44",
  },
  {
    id: 45,
    userId: 45,
    userName: "Gabriela Coleman",
    userEmail: "kennethbrown@hotmail.com",
    make: "Hyundai",
    model: "Tucson",
    year: 2020,
    pricePerDay: 82.71,
    location: "Stevensview, MO",
    description: "It argue his billion glass.",
    features: ["Backup Camera", "Sunroof", "Heated Seats"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-08-06T00:54:46",
    updatedAt: "2024-08-06T00:54:46",
  },
  {
    id: 46,
    userId: 46,
    userName: "Christina Cantu",
    userEmail: "whitemichelle@yahoo.com",
    make: "Tesla",
    model: "Model X",
    year: 2015,
    pricePerDay: 36.38,
    location: "Timfort, KS",
    description: "Nor rich agree hope current seat data.",
    features: ["Android Auto", "AC", "Bluetooth", "GPS"],
    status: "rejected",
    reviewedBy: "Michael Glass",
    reviewedAt: "2025-06-12T05:28:36",
    createdAt: "2025-06-28T04:53:07",
    updatedAt: "2025-06-28T04:53:07",
  },
  {
    id: 47,
    userId: 47,
    userName: "Michael Grimes",
    userEmail: "kyle66@gmail.com",
    make: "Chevrolet",
    model: "Malibu",
    year: 2021,
    pricePerDay: 79.24,
    location: "Cassidyfort, FL",
    description: "Beyond any heavy address.",
    features: [
      "AC",
      "GPS",
      "Apple CarPlay",
      "Heated Seats",
      "Leather Seats",
      "Sunroof",
    ],
    status: "approved",
    reviewedBy: "Lisa Jones",
    reviewedAt: "2025-06-23T13:14:04",
    createdAt: "2024-10-30T06:57:21",
    updatedAt: "2024-10-30T06:57:21",
  },
  {
    id: 48,
    userId: 48,
    userName: "Robert Evans",
    userEmail: "rnielsen@turner.net",
    make: "Hyundai",
    model: "Elantra",
    year: 2022,
    pricePerDay: 44.59,
    location: "New Justinview, CA",
    description: "Write wish around actually relationship strategy see fund.",
    features: [
      "Backup Camera",
      "Heated Seats",
      "Apple CarPlay",
      "All-Wheel Drive",
      "Android Auto",
    ],
    status: "rejected",
    reviewedBy: "Christine Hansen",
    reviewedAt: "2025-01-03T12:38:59",
    createdAt: "2025-01-11T16:32:27",
    updatedAt: "2025-01-11T16:32:27",
  },
  {
    id: 49,
    userId: 49,
    userName: "Hailey Briggs",
    userEmail: "lmendez@yahoo.com",
    make: "Ford",
    model: "Focus",
    year: 2023,
    pricePerDay: 110.83,
    location: "South Anthonystad, FL",
    description: "Short information agent law subject.",
    features: [
      "Android Auto",
      "Leather Seats",
      "Apple CarPlay",
      "Heated Seats",
      "AC",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-06-10T10:36:59",
    updatedAt: "2025-06-10T10:36:59",
  },
  {
    id: 50,
    userId: 50,
    userName: "Michael Terry",
    userEmail: "rthompson@smith-padilla.com",
    make: "Audi",
    model: "Q7",
    year: 2015,
    pricePerDay: 111.5,
    location: "Diazton, AL",
    description: "Not weight election someone party reflect different watch.",
    features: ["AC", "Backup Camera", "Bluetooth", "GPS", "Sunroof"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-07-18T18:38:10",
    updatedAt: "2024-07-18T18:38:10",
  },
  {
    id: 51,
    userId: 51,
    userName: "Mary Graham",
    userEmail: "johnnyjohnson@lopez.biz",
    make: "Chevrolet",
    model: "Malibu",
    year: 2019,
    pricePerDay: 39.44,
    location: "Port Georgeberg, MS",
    description: "Choice successful rate such.",
    features: ["Leather Seats", "Android Auto", "Heated Seats"],
    status: "approved",
    reviewedBy: "Tommy Colon",
    reviewedAt: "2025-02-20T11:10:20",
    createdAt: "2025-05-15T18:38:36",
    updatedAt: "2025-05-15T18:38:36",
  },
  {
    id: 52,
    userId: 52,
    userName: "Brianna Osborne",
    userEmail: "joe94@gmail.com",
    make: "Hyundai",
    model: "Santa Fe",
    year: 2024,
    pricePerDay: 97.87,
    location: "Mckinneyshire, CO",
    description: "Wind simple matter sometimes these.",
    features: ["Apple CarPlay", "Cruise Control", "Heated Seats"],
    status: "approved",
    reviewedBy: "Angela Wang",
    reviewedAt: "2025-03-11T22:55:05",
    createdAt: "2024-10-31T10:17:09",
    updatedAt: "2024-10-31T10:17:09",
  },
  {
    id: 53,
    userId: 53,
    userName: "James Sharp",
    userEmail: "matthew51@gmail.com",
    make: "Ford",
    model: "Escape",
    year: 2020,
    pricePerDay: 84.41,
    location: "Lake Annamouth, SC",
    description: "Walk series peace teacher manage then.",
    features: ["Cruise Control", "Heated Seats", "All-Wheel Drive"],
    status: "approved",
    reviewedBy: "Brandi Powell",
    reviewedAt: "2025-01-30T13:21:12",
    createdAt: "2024-07-21T00:16:05",
    updatedAt: "2024-07-21T00:16:05",
  },
  {
    id: 54,
    userId: 54,
    userName: "Jennifer Smith",
    userEmail: "krystalchavez@ayala.com",
    make: "Hyundai",
    model: "Tucson",
    year: 2022,
    pricePerDay: 109.47,
    location: "West Andrew, MT",
    description: "Purpose show hot lose buy rock world production.",
    features: ["Sunroof", "Bluetooth", "All-Wheel Drive"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-08-26T10:26:56",
    updatedAt: "2024-08-26T10:26:56",
  },
  {
    id: 55,
    userId: 55,
    userName: "Elizabeth Moore",
    userEmail: "shannonwilson@velez.com",
    make: "Audi",
    model: "A4",
    year: 2022,
    pricePerDay: 92.31,
    location: "Paigeburgh, AR",
    description: "Price certain fight program firm.",
    features: [
      "Cruise Control",
      "Sunroof",
      "All-Wheel Drive",
      "Leather Seats",
      "GPS",
      "Apple CarPlay",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-03-24T08:02:33",
    updatedAt: "2025-03-24T08:02:33",
  },
  {
    id: 56,
    userId: 56,
    userName: "Emily Olson",
    userEmail: "ray21@gmail.com",
    make: "BMW",
    model: "X5",
    year: 2017,
    pricePerDay: 83.02,
    location: "Alvaradohaven, NC",
    description: "Fall action major grow lawyer letter detail.",
    features: [
      "Apple CarPlay",
      "Sunroof",
      "Backup Camera",
      "Bluetooth",
      "Leather Seats",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-05-31T09:34:47",
    updatedAt: "2025-05-31T09:34:47",
  },
  {
    id: 57,
    userId: 57,
    userName: "Gina Perkins MD",
    userEmail: "richardrobinson@yahoo.com",
    make: "Honda",
    model: "Accord",
    year: 2017,
    pricePerDay: 114.93,
    location: "Taylorhaven, WI",
    description: "Certain free worker door provide another plan.",
    features: [
      "Leather Seats",
      "Backup Camera",
      "Apple CarPlay",
      "Bluetooth",
      "AC",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-10-03T03:29:47",
    updatedAt: "2024-10-03T03:29:47",
  },
  {
    id: 58,
    userId: 58,
    userName: "Arthur Perez",
    userEmail: "kelleyerin@yahoo.com",
    make: "Toyota",
    model: "Camry",
    year: 2021,
    pricePerDay: 90.51,
    location: "New Lindaview, SC",
    description: "Yard dream determine compare.",
    features: ["GPS", "Android Auto", "Leather Seats", "Heated Seats", "AC"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-06-05T08:27:02",
    updatedAt: "2025-06-05T08:27:02",
  },
  {
    id: 59,
    userId: 59,
    userName: "Connie Hodge",
    userEmail: "deborahbailey@yahoo.com",
    make: "Nissan",
    model: "Murano",
    year: 2018,
    pricePerDay: 98.78,
    location: "Kiaraberg, IN",
    description: "Tree main activity teacher white.",
    features: [
      "Sunroof",
      "Cruise Control",
      "Backup Camera",
      "AC",
      "Android Auto",
    ],
    status: "approved",
    reviewedBy: "Steven Adkins",
    reviewedAt: "2025-02-07T17:06:26",
    createdAt: "2024-12-16T18:21:44",
    updatedAt: "2024-12-16T18:21:44",
  },
  {
    id: 60,
    userId: 60,
    userName: "Joshua Caldwell",
    userEmail: "matthewmckinney@estrada.biz",
    make: "Toyota",
    model: "Camry",
    year: 2016,
    pricePerDay: 67.96,
    location: "Lake Ashleymouth, NM",
    description: "Apply at upon drug agency.",
    features: [
      "Leather Seats",
      "Android Auto",
      "Cruise Control",
      "AC",
      "Backup Camera",
    ],
    status: "rejected",
    reviewedBy: "Catherine Diaz",
    reviewedAt: "2025-02-03T16:47:41",
    createdAt: "2025-05-01T03:51:27",
    updatedAt: "2025-05-01T03:51:27",
  },
  {
    id: 61,
    userId: 61,
    userName: "Christopher Heath",
    userEmail: "lewisvictor@nunez.com",
    make: "Kia",
    model: "Sorento",
    year: 2017,
    pricePerDay: 59.45,
    location: "Lake Willie, NH",
    description: "Drive eat right care avoid space might security.",
    features: ["All-Wheel Drive", "GPS", "Heated Seats"],
    status: "rejected",
    reviewedBy: "Maria Mack",
    reviewedAt: "2025-02-24T04:47:41",
    createdAt: "2024-10-31T15:49:56",
    updatedAt: "2024-10-31T15:49:56",
  },
  {
    id: 62,
    userId: 62,
    userName: "Robin Gross",
    userEmail: "powerssteven@johnson-smith.biz",
    make: "Audi",
    model: "Q5",
    year: 2022,
    pricePerDay: 83.62,
    location: "Courtneyside, NJ",
    description: "Either discover friend this young usually.",
    features: ["Android Auto", "Apple CarPlay", "AC"],
    status: "rejected",
    reviewedBy: "Nicholas Richmond",
    reviewedAt: "2025-06-01T17:57:47",
    createdAt: "2025-01-25T17:17:34",
    updatedAt: "2025-01-25T17:17:34",
  },
  {
    id: 63,
    userId: 63,
    userName: "Jon Atkins",
    userEmail: "lhogan@perez.biz",
    make: "Nissan",
    model: "Altima",
    year: 2022,
    pricePerDay: 70.35,
    location: "Karenfort, NY",
    description: "Beautiful risk bad economic practice officer seem show.",
    features: ["AC", "Bluetooth", "Sunroof", "Cruise Control"],
    status: "approved",
    reviewedBy: "Amy Oliver",
    reviewedAt: "2025-05-17T15:08:07",
    createdAt: "2025-04-03T20:11:14",
    updatedAt: "2025-04-03T20:11:14",
  },
  {
    id: 64,
    userId: 64,
    userName: "Patrick Yoder",
    userEmail: "ivanrodriguez@yahoo.com",
    make: "Toyota",
    model: "RAV4",
    year: 2018,
    pricePerDay: 110.67,
    location: "East Vicki, WY",
    description: "Different side hear candidate mouth writer concern.",
    features: [
      "All-Wheel Drive",
      "Android Auto",
      "Cruise Control",
      "Apple CarPlay",
      "Heated Seats",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-05-29T16:04:21",
    updatedAt: "2025-05-29T16:04:21",
  },
  {
    id: 65,
    userId: 65,
    userName: "Erin Baker",
    userEmail: "laura68@anderson.com",
    make: "Kia",
    model: "Sportage",
    year: 2023,
    pricePerDay: 114.77,
    location: "South Stephanie, WY",
    description: "Take give personal relationship.",
    features: [
      "Sunroof",
      "Cruise Control",
      "GPS",
      "Leather Seats",
      "AC",
      "Heated Seats",
    ],
    status: "rejected",
    reviewedBy: "Jessica Johnson",
    reviewedAt: "2025-07-07T00:49:52",
    createdAt: "2024-11-18T22:21:45",
    updatedAt: "2024-11-18T22:21:45",
  },
  {
    id: 66,
    userId: 66,
    userName: "Lonnie Peck",
    userEmail: "pclark@simmons.com",
    make: "Honda",
    model: "Accord",
    year: 2019,
    pricePerDay: 47.44,
    location: "Sarahfort, PA",
    description: "Million before can attention child.",
    features: ["Leather Seats", "GPS", "Apple CarPlay", "Backup Camera"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-10-13T08:03:09",
    updatedAt: "2024-10-13T08:03:09",
  },
  {
    id: 67,
    userId: 67,
    userName: "Chelsea Stafford",
    userEmail: "hgreen@gamble-davis.biz",
    make: "Nissan",
    model: "Altima",
    year: 2015,
    pricePerDay: 113.46,
    location: "Rachelmouth, MS",
    description: "Way investment generation room behind.",
    features: [
      "GPS",
      "All-Wheel Drive",
      "AC",
      "Cruise Control",
      "Backup Camera",
      "Android Auto",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-11-08T19:22:06",
    updatedAt: "2024-11-08T19:22:06",
  },
  {
    id: 68,
    userId: 68,
    userName: "Lauren Powell",
    userEmail: "melanielewis@yahoo.com",
    make: "Chevrolet",
    model: "Equinox",
    year: 2020,
    pricePerDay: 91.4,
    location: "Melindastad, AL",
    description: "Game art its dream them.",
    features: [
      "Bluetooth",
      "All-Wheel Drive",
      "Heated Seats",
      "Leather Seats",
      "AC",
    ],
    status: "approved",
    reviewedBy: "Sarah Smith",
    reviewedAt: "2025-03-16T11:28:10",
    createdAt: "2025-03-30T08:12:25",
    updatedAt: "2025-03-30T08:12:25",
  },
  {
    id: 69,
    userId: 69,
    userName: "Renee Dawson",
    userEmail: "tonyabaker@hotmail.com",
    make: "Hyundai",
    model: "Elantra",
    year: 2022,
    pricePerDay: 110.3,
    location: "Port Kim, AZ",
    description: "Our program operation leave.",
    features: ["Apple CarPlay", "GPS", "Sunroof", "Backup Camera"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-09-02T22:17:08",
    updatedAt: "2024-09-02T22:17:08",
  },
  {
    id: 70,
    userId: 70,
    userName: "Kelly Ross",
    userEmail: "sarahortega@yahoo.com",
    make: "Nissan",
    model: "Altima",
    year: 2015,
    pricePerDay: 95.61,
    location: "East Thomas, CO",
    description: "Professor thought treat scientist senior region.",
    features: ["Cruise Control", "AC", "Apple CarPlay"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-07-15T07:06:36",
    updatedAt: "2024-07-15T07:06:36",
  },
  {
    id: 71,
    userId: 71,
    userName: "Timothy Jackson",
    userEmail: "wbennett@horton.biz",
    make: "Tesla",
    model: "Model 3",
    year: 2021,
    pricePerDay: 113.86,
    location: "North Thomaston, ND",
    description: "Side movement exist institution leg key pay laugh.",
    features: [
      "Bluetooth",
      "All-Wheel Drive",
      "AC",
      "Apple CarPlay",
      "Heated Seats",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-06-12T12:20:15",
    updatedAt: "2025-06-12T12:20:15",
  },
  {
    id: 72,
    userId: 72,
    userName: "Matthew Smith",
    userEmail: "craig61@holt.biz",
    make: "Honda",
    model: "Civic",
    year: 2018,
    pricePerDay: 80.32,
    location: "Leeburgh, NE",
    description: "Believe suggest pass your administration.",
    features: ["Android Auto", "Apple CarPlay", "GPS", "AC"],
    status: "rejected",
    reviewedBy: "Melinda Guerrero",
    reviewedAt: "2025-05-08T15:56:26",
    createdAt: "2024-07-17T04:15:13",
    updatedAt: "2024-07-17T04:15:13",
  },
  {
    id: 73,
    userId: 73,
    userName: "Stephen Williams",
    userEmail: "ilawrence@washington.net",
    make: "Kia",
    model: "Sorento",
    year: 2019,
    pricePerDay: 68.68,
    location: "New Melissaburgh, UT",
    description: "We science already policy help have hundred.",
    features: ["Cruise Control", "Bluetooth", "Android Auto", "Leather Seats"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-11-09T21:40:44",
    updatedAt: "2024-11-09T21:40:44",
  },
  {
    id: 74,
    userId: 74,
    userName: "Nicole Rios",
    userEmail: "millerjames@robinson.net",
    make: "Kia",
    model: "Sorento",
    year: 2016,
    pricePerDay: 52.36,
    location: "Elliotttown, SD",
    description: "Arm leg green.",
    features: ["Bluetooth", "Apple CarPlay", "Cruise Control", "Android Auto"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-01-10T22:45:21",
    updatedAt: "2025-01-10T22:45:21",
  },
  {
    id: 75,
    userId: 75,
    userName: "Margaret Jones",
    userEmail: "toddwayne@yahoo.com",
    make: "Audi",
    model: "Q7",
    year: 2017,
    pricePerDay: 58.2,
    location: "Guerrafort, TN",
    description: "Deal tend might team.",
    features: [
      "Cruise Control",
      "Apple CarPlay",
      "Leather Seats",
      "Backup Camera",
      "GPS",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-10-20T16:56:54",
    updatedAt: "2024-10-20T16:56:54",
  },
  {
    id: 76,
    userId: 76,
    userName: "Michelle Evans",
    userEmail: "lowejoseph@hotmail.com",
    make: "Honda",
    model: "Civic",
    year: 2020,
    pricePerDay: 74.81,
    location: "East Calvin, IA",
    description: "Natural four hope time.",
    features: [
      "Heated Seats",
      "All-Wheel Drive",
      "Apple CarPlay",
      "Bluetooth",
      "Cruise Control",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-03-20T08:25:31",
    updatedAt: "2025-03-20T08:25:31",
  },
  {
    id: 77,
    userId: 77,
    userName: "Ethan Sosa",
    userEmail: "sestes@lopez.net",
    make: "Toyota",
    model: "Corolla",
    year: 2020,
    pricePerDay: 30.34,
    location: "Lopezbury, KS",
    description: "Democrat unit whose nothing.",
    features: [
      "All-Wheel Drive",
      "Cruise Control",
      "Backup Camera",
      "Leather Seats",
    ],
    status: "approved",
    reviewedBy: "Sarah Serrano",
    reviewedAt: "2025-02-24T08:39:36",
    createdAt: "2024-10-14T07:34:00",
    updatedAt: "2024-10-14T07:34:00",
  },
  {
    id: 78,
    userId: 78,
    userName: "Matthew York",
    userEmail: "tashajones@russell-wu.com",
    make: "Honda",
    model: "CR-V",
    year: 2021,
    pricePerDay: 73.59,
    location: "Annville, IL",
    description: "Painting certain base water safe authority head.",
    features: ["All-Wheel Drive", "Android Auto", "Apple CarPlay"],
    status: "rejected",
    reviewedBy: "Joseph Miller",
    reviewedAt: "2025-04-16T15:37:43",
    createdAt: "2025-01-11T08:28:50",
    updatedAt: "2025-01-11T08:28:50",
  },
  {
    id: 79,
    userId: 79,
    userName: "Dwayne Gardner",
    userEmail: "john58@buchanan.biz",
    make: "Honda",
    model: "Civic",
    year: 2023,
    pricePerDay: 109.81,
    location: "Kingshire, RI",
    description: "Interesting middle vote television analysis be.",
    features: [
      "Backup Camera",
      "GPS",
      "Bluetooth",
      "All-Wheel Drive",
      "Sunroof",
      "Android Auto",
    ],
    status: "approved",
    reviewedBy: "Daniel Moreno",
    reviewedAt: "2025-03-28T16:42:23",
    createdAt: "2025-06-08T05:20:24",
    updatedAt: "2025-06-08T05:20:24",
  },
  {
    id: 80,
    userId: 80,
    userName: "Alexis Martinez",
    userEmail: "aprilvasquez@hotmail.com",
    make: "Hyundai",
    model: "Elantra",
    year: 2016,
    pricePerDay: 36.21,
    location: "Lake Justin, OH",
    description: "Cut page world bill.",
    features: ["Android Auto", "Apple CarPlay", "Backup Camera", "GPS"],
    status: "rejected",
    reviewedBy: "Vanessa Allen",
    reviewedAt: "2025-06-24T03:46:48",
    createdAt: "2025-07-02T02:14:53",
    updatedAt: "2025-07-02T02:14:53",
  },
  {
    id: 81,
    userId: 81,
    userName: "Kevin Foster",
    userEmail: "ehernandez@perez.com",
    make: "Tesla",
    model: "Model X",
    year: 2020,
    pricePerDay: 47.01,
    location: "Franktown, MN",
    description: "Kitchen service painting half.",
    features: [
      "Backup Camera",
      "GPS",
      "Android Auto",
      "Heated Seats",
      "Apple CarPlay",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-03-19T21:05:37",
    updatedAt: "2025-03-19T21:05:37",
  },
  {
    id: 82,
    userId: 82,
    userName: "Betty Pruitt",
    userEmail: "zfrancis@hotmail.com",
    make: "Toyota",
    model: "Corolla",
    year: 2018,
    pricePerDay: 62.9,
    location: "Samanthaton, AZ",
    description: "Lawyer green significant.",
    features: [
      "Cruise Control",
      "Android Auto",
      "AC",
      "All-Wheel Drive",
      "Leather Seats",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-05-11T18:14:34",
    updatedAt: "2025-05-11T18:14:34",
  },
  {
    id: 83,
    userId: 83,
    userName: "Frances Harris",
    userEmail: "tbaker@gmail.com",
    make: "Nissan",
    model: "Murano",
    year: 2017,
    pricePerDay: 37.67,
    location: "East Nicoleport, ND",
    description: "Down organization wish but.",
    features: ["AC", "Leather Seats", "All-Wheel Drive", "Apple CarPlay"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-06-16T00:35:34",
    updatedAt: "2025-06-16T00:35:34",
  },
  {
    id: 84,
    userId: 84,
    userName: "Linda Hinton",
    userEmail: "jeremywu@walsh.com",
    make: "Kia",
    model: "Soul",
    year: 2017,
    pricePerDay: 83.81,
    location: "Lake Eric, CO",
    description: "Bag well report few.",
    features: [
      "Android Auto",
      "Bluetooth",
      "Backup Camera",
      "AC",
      "Heated Seats",
    ],
    status: "rejected",
    reviewedBy: "Mr. Andrew Harris",
    reviewedAt: "2025-02-09T08:17:53",
    createdAt: "2024-07-21T09:23:35",
    updatedAt: "2024-07-21T09:23:35",
  },
  {
    id: 85,
    userId: 85,
    userName: "Katherine Bailey",
    userEmail: "englishnicholas@gmail.com",
    make: "Nissan",
    model: "Altima",
    year: 2019,
    pricePerDay: 60.46,
    location: "West Toddview, MI",
    description: "Service picture I story worry perhaps laugh.",
    features: [
      "Backup Camera",
      "AC",
      "Bluetooth",
      "All-Wheel Drive",
      "Apple CarPlay",
      "Android Auto",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-10-26T21:37:13",
    updatedAt: "2024-10-26T21:37:13",
  },
  {
    id: 86,
    userId: 86,
    userName: "Madeline Rose",
    userEmail: "austinmoore@taylor.com",
    make: "Nissan",
    model: "Rogue",
    year: 2024,
    pricePerDay: 79.83,
    location: "New Loriville, WI",
    description: "Treat expect rather decade happen give feeling.",
    features: [
      "Apple CarPlay",
      "Cruise Control",
      "All-Wheel Drive",
      "Android Auto",
      "Sunroof",
      "Leather Seats",
    ],
    status: "approved",
    reviewedBy: "Maria Jones",
    reviewedAt: "2025-03-26T01:16:51",
    createdAt: "2025-02-18T01:15:03",
    updatedAt: "2025-02-18T01:15:03",
  },
  {
    id: 87,
    userId: 87,
    userName: "Harold Blair",
    userEmail: "fosterkarina@mitchell-lee.com",
    make: "Hyundai",
    model: "Tucson",
    year: 2021,
    pricePerDay: 48.92,
    location: "Richardton, WV",
    description: "Something feeling home history contain.",
    features: [
      "GPS",
      "Apple CarPlay",
      "Bluetooth",
      "Backup Camera",
      "Android Auto",
      "Leather Seats",
    ],
    status: "rejected",
    reviewedBy: "Dawn Patrick",
    reviewedAt: "2025-04-30T08:15:39",
    createdAt: "2024-10-21T22:04:10",
    updatedAt: "2024-10-21T22:04:10",
  },
  {
    id: 88,
    userId: 88,
    userName: "Andrea Eaton",
    userEmail: "stephaniehansen@roberson.biz",
    make: "Chevrolet",
    model: "Tahoe",
    year: 2021,
    pricePerDay: 97.16,
    location: "Kimshire, NJ",
    description: "Player behind better also.",
    features: ["Heated Seats", "Cruise Control", "Backup Camera"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-01-11T12:59:25",
    updatedAt: "2025-01-11T12:59:25",
  },
  {
    id: 89,
    userId: 89,
    userName: "Dylan Miller",
    userEmail: "lporter@hotmail.com",
    make: "Honda",
    model: "CR-V",
    year: 2020,
    pricePerDay: 56.29,
    location: "Cooktown, WY",
    description: "Have edge time including history.",
    features: ["All-Wheel Drive", "Apple CarPlay", "Cruise Control"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-05-28T10:44:36",
    updatedAt: "2025-05-28T10:44:36",
  },
  {
    id: 90,
    userId: 90,
    userName: "Darrell Barrett",
    userEmail: "aschmidt@gmail.com",
    make: "Honda",
    model: "Accord",
    year: 2016,
    pricePerDay: 38.07,
    location: "Port Rebecca, AZ",
    description: "In often people choice involve.",
    features: ["Heated Seats", "All-Wheel Drive", "Sunroof"],
    status: "rejected",
    reviewedBy: "Brianna Harrison",
    reviewedAt: "2025-02-05T14:43:20",
    createdAt: "2024-10-21T01:28:58",
    updatedAt: "2024-10-21T01:28:58",
  },
  {
    id: 91,
    userId: 91,
    userName: "Fred Mann",
    userEmail: "ebooth@gmail.com",
    make: "Ford",
    model: "Escape",
    year: 2016,
    pricePerDay: 106.61,
    location: "Stevensview, NJ",
    description: "Seven could guy expert technology goal owner sell.",
    features: [
      "AC",
      "Apple CarPlay",
      "Heated Seats",
      "All-Wheel Drive",
      "Leather Seats",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-03-05T05:00:14",
    updatedAt: "2025-03-05T05:00:14",
  },
  {
    id: 92,
    userId: 92,
    userName: "Kristy Stephens",
    userEmail: "warmstrong@williams.com",
    make: "BMW",
    model: "X3",
    year: 2024,
    pricePerDay: 66.6,
    location: "West Josephmouth, HI",
    description: "Believe start great.",
    features: ["AC", "Heated Seats", "Android Auto"],
    status: "approved",
    reviewedBy: "Ashley Wallace",
    reviewedAt: "2025-02-02T18:36:28",
    createdAt: "2025-02-05T00:25:03",
    updatedAt: "2025-02-05T00:25:03",
  },
  {
    id: 93,
    userId: 93,
    userName: "Jeffery Ortiz",
    userEmail: "aliciaflores@hotmail.com",
    make: "BMW",
    model: "3 Series",
    year: 2024,
    pricePerDay: 81.37,
    location: "Porterhaven, IN",
    description: "Indeed state from travel.",
    features: [
      "Cruise Control",
      "Android Auto",
      "Bluetooth",
      "Heated Seats",
      "All-Wheel Drive",
      "GPS",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-10-26T16:21:15",
    updatedAt: "2024-10-26T16:21:15",
  },
  {
    id: 94,
    userId: 94,
    userName: "Caroline Potter",
    userEmail: "gardnerlance@smith.net",
    make: "Chevrolet",
    model: "Equinox",
    year: 2022,
    pricePerDay: 100.72,
    location: "Port Charles, NM",
    description: "Manage worry attorney state.",
    features: [
      "All-Wheel Drive",
      "GPS",
      "Cruise Control",
      "AC",
      "Bluetooth",
      "Backup Camera",
    ],
    status: "approved",
    reviewedBy: "Sarah Morrison",
    reviewedAt: "2025-02-02T13:33:40",
    createdAt: "2025-04-23T09:09:07",
    updatedAt: "2025-04-23T09:09:07",
  },
  {
    id: 95,
    userId: 95,
    userName: "Cynthia Petty",
    userEmail: "fwilliams@gmail.com",
    make: "BMW",
    model: "3 Series",
    year: 2015,
    pricePerDay: 73.88,
    location: "Smithmouth, UT",
    description: "Short billion cultural next recently group morning pattern.",
    features: [
      "Android Auto",
      "Apple CarPlay",
      "Cruise Control",
      "Bluetooth",
      "GPS",
      "Leather Seats",
    ],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2024-10-15T07:09:05",
    updatedAt: "2024-10-15T07:09:05",
  },
  {
    id: 96,
    userId: 96,
    userName: "Jacqueline Wagner",
    userEmail: "derek32@soto-patrick.com",
    make: "BMW",
    model: "X5",
    year: 2019,
    pricePerDay: 57.49,
    location: "Fernandoshire, CA",
    description: "Man town part.",
    features: ["Sunroof", "All-Wheel Drive", "Cruise Control", "Bluetooth"],
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
    createdAt: "2025-03-19T18:05:47",
    updatedAt: "2025-03-19T18:05:47",
  },
  {
    id: 97,
    userId: 97,
    userName: "John Ellis",
    userEmail: "andrea28@smith-haynes.com",
    make: "Audi",
    model: "A4",
    year: 2024,
    pricePerDay: 35.14,
    location: "Port Susanmouth, SC",
    description: "History surface decade figure situation unit.",
    features: ["Cruise Control", "Apple CarPlay", "All-Wheel Drive"],
    status: "approved",
    reviewedBy: "Laura Freeman",
    reviewedAt: "2025-04-01T10:16:02",
    createdAt: "2025-01-04T03:13:04",
    updatedAt: "2025-01-04T03:13:04",
  },
  {
    id: 98,
    userId: 98,
    userName: "Hunter Martinez",
    userEmail: "xmejia@hotmail.com",
    make: "Honda",
    model: "Civic",
    year: 2024,
    pricePerDay: 44.17,
    location: "West Christopher, SD",
    description: "Likely least move.",
    features: [
      "Heated Seats",
      "Bluetooth",
      "AC",
      "Apple CarPlay",
      "Backup Camera",
      "GPS",
    ],
    status: "approved",
    reviewedBy: "Mary Turner",
    reviewedAt: "2025-03-29T02:03:42",
    createdAt: "2025-07-07T01:28:20",
    updatedAt: "2025-07-07T01:28:20",
  },
  {
    id: 99,
    userId: 99,
    userName: "Brian Pollard",
    userEmail: "brownsusan@yahoo.com",
    make: "Kia",
    model: "Soul",
    year: 2023,
    pricePerDay: 108.05,
    location: "Boltonfort, AR",
    description: "Lead official message author husband remember back.",
    features: [
      "AC",
      "All-Wheel Drive",
      "Bluetooth",
      "Cruise Control",
      "Leather Seats",
    ],
    status: "approved",
    reviewedBy: "Andre Rodriguez",
    reviewedAt: "2025-05-28T05:31:58",
    createdAt: "2025-05-11T08:01:06",
    updatedAt: "2025-05-11T08:01:06",
  },
  {
    id: 100,
    userId: 100,
    userName: "Chelsea Hill",
    userEmail: "dawn06@wilson.com",
    make: "BMW",
    model: "X5",
    year: 2021,
    pricePerDay: 119.53,
    location: "Thompsonburgh, ID",
    description: "Mission child someone raise.",
    features: [
      "All-Wheel Drive",
      "AC",
      "Android Auto",
      "Heated Seats",
      "Backup Camera",
    ],
    status: "rejected",
    reviewedBy: "Brian Brown",
    reviewedAt: "2025-07-05T17:37:28",
    createdAt: "2025-07-05T00:37:18",
    updatedAt: "2025-07-05T00:37:18",
  },
];

export const getData = async (
  page: number,
  limit: number,
  status: string | null
): Promise<{ data: Listing[]; totalCount: number; totalPages: number }> => {
  const skip = (page - 1) * limit;

  if (status) {
    const filteredData = listings.filter(
      (listing) => listing.status === status
    );
    return {
      totalCount: filteredData.length,
      totalPages: Math.ceil(filteredData.length / limit),
      data: filteredData.slice(skip, skip + limit),
    };
  }
  return {
    totalCount: listings.length,
    totalPages: Math.ceil(listings.length / limit),
    data: listings.slice(skip, skip + limit),
  };
};

//admin action logs
export const adminActions: AdminAction[] = [];

export const getLogs = async (): Promise<AdminAction[]> => {
  return adminActions;
};

// export async function getListingById(id: number): Promise<Listing | null> {
//   return listings.find((listing) => listing.id === id) || null
// }

// export async function updateListingStatus(
//   id: number,
//   status: "approved" | "rejected",
//   adminNotes: string,
//   adminName: string,
// ): Promise<boolean> {
//   const listingIndex = listings.findIndex((l) => l.id === id)
//   if (listingIndex === -1) return false

//   listings[listingIndex] = {
//     ...listings[listingIndex],
//     status,
//     adminNotes: adminNotes,
//     reviewedBy: adminName,
//     reviewedAt: new Date().toISOString(),
//     updatedAt: new Date().toISOString(),
//   }

//   // Add admin action
//   adminActions.push({
//     id: adminActions.length + 1,
//     listing_id: id,
//     admin_name: adminName,
//     action: status,
//     notes: adminNotes,
//     createdAt: new Date().toISOString(),
//   })

//   return true
// }

// export async function updateListing(id: number, updates: Partial<Listing>): Promise<boolean> {
//   const listingIndex = listings.findIndex((l) => l.id === id)
//   if (listingIndex === -1) return false

//   listings[listingIndex] = {
//     ...listings[listingIndex],
//     ...updates,
//     updatedAt: new Date().toISOString(),
//   }

//   return true
// }
